; This file was auto-generated by drush_make
core = 6.x

api = 2
projects[drupal][version] = "6.38"

; Modules
projects[admin_menu][version] = "1.9"
projects[autologout][version] = "2.6"
projects[backup_migrate][version] = "2.8"
projects[better_formats][version] = "1.2"
projects[captcha][version] = "2.6"
projects[cck][version] = "2.9"
projects[computed_field][version] = "1.0"
projects[content_taxonomy][version] = "1.0-rc2"
projects[css_injector][version] = "1.4"
projects[ctools][version] = "1.15"
projects[elysia_cron][version] = "2.1"
projects[email][version] = "1.4"
projects[feeds][version] = "1.0-beta13"
projects[filefield][version] = "3.14"
projects[google_analytics][version] = "4.1"
projects[imagefield][version] = "3.11"
projects[imagepicker][version] = "2.16"
projects[imce_wysiwyg][version] = "1.1"
projects[imce][version] = "2.7"
projects[insert_view][version] = "2.x-dev"
projects[invisimail][version] = "1.3"
projects[job_scheduler][version] = "1.0-beta3"
projects[js_injector][version] = "1.1"
projects[link][version] = "2.11"
projects[linkchecker][version] = "2.8"
projects[menu_attributes][version] = "1.4"
projects[mollom][version] = "2.12"
projects[nice_menus][version] = "2.1"
projects[pathauto][version] = "1.6"
projects[seo_checklist][version] = "3.0"
projects[site_verify][version] = "1.0"
projects[taxonomy_manager][version] = "2.3"
projects[token][version] = "1.19"
projects[views][version] = "2.18"
projects[webform][version] = "3.23"
projects[wysiwyg][version] = "2.4"
projects[xmlsitemap][version] = "2.1"

; Please fill the following out. Type may be one of get, cvs, git, bzr or svn,
; and url is the url of the download.
projects[ares][type] = "module"
projects[ares][download][type] = "svn"
projects[ares][download][url] =
        "https://svn.library.cornell.edu/ares/trunk/module"


; Please fill the following out. Type may be one of get, cvs, git, bzr or svn,
; and url is the url of the download.
projects[cu_template][download][type] = "svn"
projects[cu_template][download][url] =
        "https://svn.library.cornell.edu/cu_template/trunk/module"

projects[cu_template][type] = "module"
projects[cu_template][subdir] = "custom"

; Please fill the following out. Type may be one of get, cvs, git, bzr or svn,
; and url is the url of the download.
projects[cul_common][type] = "module"
projects[cul_common][download][type] = "svn"
projects[cul_common][download][url] =
        "https://svn.library.cornell.edu/cul_common/trunk/module"
projects[cul_common][revision] = "HEAD"


; Please fill the following out. Type may be one of get, cvs, git, bzr or svn,
; and url is the url of the download.
projects[cul_login][type] = "module"
projects[cul_login][download][type] = "svn"
projects[cul_login][download][url] =
        "https://svn.library.cornell.edu/cul_login/trunk/module"

projects[cul_login][revision] = "HEAD"
projects[cul_login][subdir] = "custom"


; Please fill the following out. Type may be one of get, cvs, git, bzr or svn,
; and url is the url of the download.
projects[goosacul][download][type] = "svn"
projects[goosacul][download][url] = "https://svn.library.cornell.edu/goosacul/trunk/module"
projects[goosacul][type] = "module"
projects[goosacul][subdir] = "custom"
projects[goosacul][revision] = "HEAD"


; Please fill the following out. Type may be one of get, cvs, git, bzr or svn,
; and url is the url of the download.
projects[journal_list][type] = "module"
projects[journal_list][download][type] = "svn"
projects[journal_list][download][url] =
        "https://svn.library.cornell.edu/journal_list/trunk/module"

projects[journal_list][revision] = "HEAD"

; Please fill the following out. Type may be one of get, cvs, git, bzr or svn,
; and url is the url of the download.
projects[staff_directory][type] = "module"
projects[staff_directory][download][type] = "svn"
projects[staff_directory][download][url] =
        "https://svn.library.cornell.edu/staff_directory/trunk/module"
projects[staff_directory][revision] = "HEAD"

; Please fill the following out. Type may be one of get, cvs, git, bzr or svn,
; and url is the url of the download.
projects[views_menu_sort][type] = "module"
projects[views_menu_sort][download][type] = "svn"
projects[views_menu_sort][download][url] =
        "https://svn.library.cornell.edu/views_menu_sort/trunk/module"


; Themes
; Please fill the following out. Type may be one of get, cvs, git, bzr or svn,
; and url is the url of the download.
projects[music_library][download][type] = "svn"
projects[music_library][download][url] =
 "https://svn.library.cornell.edu/music_library/trunk/theme"
projects[music_library][type] = "theme"

;Libraries
libraries[tinymce][download][type] = "svn"
libraries[tinymce][download][url] = "https://svn.library.cornell.edu/tinymce-clone/trunk"
libraries[tinymce][directory_name] = "tinymce"

